### ISSUE TITLE
TOKEN过期之后笔记内容丢失

### ISSUE THREAD

**Issue by TankNee** [TankNee/Memocast#109]
900s之后token如果没有刷新就会过期，此时笔记如果没有保存就有可能丢失更改

**Comment by boygao1992** [comment]
Linux AppImage 2.1.5没有碰到这个问题，但2.1.7频繁出现这个问题

**Comment by TankNee** [comment]
收到，已发现这个问题，你可以暂时先回退到2.1.5，2.1.6应该也有这个问题。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："Wenbo Gao ***@***.***&gt;;
发送时间：2021年8月15日(星期天) 凌晨2:10
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："TankNee ***@***.***&gt;;"Author ***@***.***&gt;;
主题：Re: [TankNee/Memocast] TOKEN过期之后笔记内容丢失 (#109)
-----------------------------------

 

 
Linux AppImage 2.1.5没有碰到这个问题，但2.1.7频繁出现这个问题
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by TankNee** [comment]
2.1.8 已经修复这个问题，请更新到最新版本。
