### ISSUE TITLE
未来会支持Docker部署吗

### ISSUE THREAD

**Issue by Autonomous120** [TankNee/Memocast#115]
有没有部署到Docker，实现自托管的计划

**Comment by TankNee** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    为知官方已经提供了笔记服务的私有部署，就是用Docker实现的，你可以去          https://wiz.cn 看看。
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                TankNee
                            
                    
                        
                            
                                    ***@***.***
                                    https://tanknee.cn
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年7月5日 ***@***.***> 写道： 




有没有部署到Docker，实现自托管的计划



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
