### ISSUE TITLE
导出笔记，无法导出图片

### ISSUE THREAD

**Issue by AriaLyy** [TankNee/Memocast#130]
我笔记中的图片是以前在为知的客户端中创建的，切换到memocast中后，导出笔记时，只能导出文字，无法导出图片
ps: 我的笔记都是markdown笔记

**Comment by TankNee** [comment]
是有这个问题，因为我暂时没有想好是把图片用base64直接嵌入笔记里导出比较好还是将笔记导出到一个单独的文件夹比较好，所以就没有做。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："lyy ***@***.***&gt;;
发送时间：2021年7月19日(星期一) 晚上10:15
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[TankNee/Memocast] 导出笔记，无法导出图片 (#130)
-----------------------------------

 

 
我笔记中的图片是以前在为知的客户端中创建的，切换到memocast中后，导出笔记时，只能导出文字，无法导出图片
 ps: 我的笔记都是markdown笔记

**Comment by AriaLyy** [comment]
个人感觉单独文件比较好吧，如果有的笔记图片比较多，并且图片都普遍偏大，那么文档是不是也变得很大了，有可能导致笔记打开慢

**Comment by TankNee** [comment]
确实，对于网页剪辑的笔记来说图片可能会非常多，不过这样的话导入其他笔记应用的兼容性就会比较差，图片再插入会相对麻烦。
我还有一个想法是通过picgo之类的工具将图片上传到图床变成网络图片，这样导出和导入其他应用都会方便，不过对普通用户不太友好。
目前是倾向于做导出到单独的文件夹。
----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："lyy ***@***.***&gt;;
发送时间：2021年7月19日(星期一) 晚上10:35
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："TankNee ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [TankNee/Memocast] 导出笔记，无法导出图片 (#130)
-----------------------------------

 

 
个人感觉单独文件比较好吧，如果有的笔记图片比较多，并且图片都普遍偏大，那么文档是不是也变得很大了，有可能导致笔记打开慢

**Comment by elfzweik** [comment]
Joplin的导出是图片在一个_resource文件夹里，同时替换导出笔记中的链接指向这个文件夹里的图片。我在Joplin中导出后，用memocast导入，开始几篇导入很好，建议考虑这种方式。
顺便提一句，我在memocast中导入joplin的导出笔记，十几篇之后的笔记就会图片导入不了。感觉是不是docker部署的为知笔记也有每月流量限制？因为我是某一篇笔记中导入成功了头部几个图片，后面的无法导入，之后的笔记全部无法导入图片。

**Comment by elfzweik** [comment]
> > Joplin的导出是图片在一个_resource文件夹里，同时替换导出笔记中的链接指向这个文件夹里的图片。我在Joplin中导出后，用memocast导入，开始几篇导入很好，建议考虑这种方式。
> > 顺便提一句，我在memocast中导入joplin的导出笔记，十几篇之后的笔记就会图片导入不了。感觉是不是docker部署的为知笔记也有每月流量限制？因为我是某一篇笔记中导入成功了头部几个图片，后面的无法导入，之后的笔记全部无法导入图片。
> 
> Memocast 并没有对Markdown文件里的图片进行上传之类的操作。所以就不存在导入失败的问题，应该是路径的问题，我有时间会优化这块的。

不是用wiznote自带的图片上传功能上传图片的吗？

**Comment by TankNee** [comment]
> > > Joplin的导出是图片在一个_resource文件夹里，同时替换导出笔记中的链接指向这个文件夹里的图片。我在Joplin中导出后，用memocast导入，开始几篇导入很好，建议考虑这种方式。
> > > 顺便提一句，我在memocast中导入joplin的导出笔记，十几篇之后的笔记就会图片导入不了。感觉是不是docker部署的为知笔记也有每月流量限制？因为我是某一篇笔记中导入成功了头部几个图片，后面的无法导入，之后的笔记全部无法导入图片。
> > 
> > 
> > Memocast 并没有对Markdown文件里的图片进行上传之类的操作。所以就不存在导入失败的问题，应该是路径的问题，我有时间会优化这块的。
> 
> 不是用wiznote自带的图片上传功能上传图片的吗？

我的意思是使用上传笔记那个功能的时候不会调用位置的API对笔记里的图片链接进行上传，所以也就是说不会对这些图片链接进行任何处理。所以就不存在流量限制。
