### ISSUE TITLE
编辑器在光标落到其它markdown语法标志符时，可以显示带标志符的markdown源码，但是标题不会。建议改成同样显示源码，加减#个数就可以调整标题等级。

### ISSUE THREAD

**Issue by elfzweik** [TankNee/Memocast#151]
非常感谢你开发了Memocast，即时同窗渲染是一个让我重新使用为知笔记账号的功能。

顺便提一下，我是同时发现的Memocast和Wiznote lite，最初选择了使用Wiznote lite，因为它启动感觉比较快，而且编辑器支持本issue中提到的光标移到标题进显示标题的源码。但是用了一段时间后发现Wiznote lite渲染器对mermaid图的支持不好，页面布局占用很大，感觉只是把代码隐藏了，但空间仍然保留着，而且配色很差，有时候背景色与字体颜色几乎一样，看不清字体。而memocast的vditor渲染得要好多了，显示效果完美。但是Memocsst也有种种不足，比如没有移动客户端、不支持wiznote lite的tag标志，启动慢等等。

两个前端都在发展的早期，还存在各种不足，希望能发展得越来越好！所以我提了一系列建议，从用户的角度提供一点反馈供优化时参考。再次感谢开发了这么好的笔记前端让我们使用。

**Comment by TankNee** [comment]
1. 我觉得直接使用快捷键比你加减 # 要方便一些，你可以直接用 <kbd>Ctrl + 1</kbd> 这样的快捷键来改变标题等级。
2. Memocast 也是支持直接查看 Markdown 源码的，只需要你把光标放到文字的最左侧，按左键就能看到标题源代码
![image](https://user-images.githubusercontent.com/43956168/129818176-4bf6b05f-110a-41f2-bcfb-ac99e4777c1e.png)

**Comment by TankNee** [comment]
> 启动慢
这个问题会考虑优化的，现在启动慢主要是因为要登陆，所以比较慢，跟网络有关。
