### ISSUE TITLE
Momocast软件启动太慢，建议优化，或者加入一点启动动画效果，提升用户体验。

### ISSUE THREAD

**Issue by elfzweik** [TankNee/Memocast#154]

**Comment by elfzweik** [comment]
在一台老的Thinkpad X230上装了Ubuntu，使用Memocast，发现打开速度快了好多，供参考。

**Comment by TankNee** [comment]
之前用的是机械硬盘吗？加载速度和硬盘速度、网络状况都有较强的联系。

**Comment by elfzweik** [comment]
正相反，之前用的是华为matebook x pro，8代i7、16G内存、固态硬盘，都比X230强得多。X230是3代i5、4G内存、机械硬盘。
