### ISSUE TITLE
连接私有部署时出现网络请求错误

### ISSUE THREAD

**Issue by CKylinMC** [TankNee/Memocast#171]
尝试连接到私有部署时出现网络请求错误。

没有在安装目录下找到 #166 里面提到的logs文件夹。

客户端：
Windows 11
Memocast 2.2.0

服务端：
使用官方docker部署
服务端版本: 1.0.26
使用反向代理到网页端口的方式带HTTPS部署

这是我第一次使用为知笔记的docker端，我不确定是否是我部署存在问题导致的。私有部署的网页版没有问题。

**Comment by TankNee** [comment]
检查一下你的私有部署网址是否有问题，能否正常登陆？los文件一般是在c盘的那个目录下面，AppData，Memocast啥的，具体我记不清楚了，之前也有几个issue是和这相关的，基本上是网址给错了或者网页ssl证书有问题。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："CKylinMC ***@***.***&gt;;
发送时间：2021年12月18日(星期六) 中午1:18
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："Subscribed ***@***.***&gt;;
主题：[TankNee/Memocast] 连接私有部署时出现网络请求错误 (Issue #171)
-----------------------------------

 

 
尝试连接到私有部署时出现网络请求错误。
 
没有在安装目录下找到 #166 里面提到的logs文件夹。
 
客户端：
 Windows 11
 Memocast 2.2.0
 
服务端：
 使用官方docker部署
 服务端版本: 1.0.26
 使用反向代理到网页端口的方式带HTTPS部署
 
这是我第一次使用为知笔记的docker端，我不确定是否是我部署存在问题导致的。私有部署的网页版没有问题。
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CKylinMC** [comment]
logs找到了，提示的是证书已过期...

但是我浏览器里确实是可以打开的，没有任何错误。

另外，日志中**明文记录**了我的账户信息...

**Comment by TankNee** [comment]
确实是明文。。。因为为知的登录接口也是明文，所以就没做加密，有时间我想想怎么搞的安全一点。登录不上去应该就是证书的问题了，网页估计是忽略掉了吧，你可以试试用http登陆。

----------

该邮件从移动设备发送


--------------原始邮件--------------
发件人："CKylinMC ***@***.***&gt;;
发送时间：2021年12月18日(星期六) 中午1:56
收件人："TankNee/Memocast" ***@***.***&gt;;
抄送："TankNee ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [TankNee/Memocast] 连接私有部署时出现网络请求错误 (Issue #171)
-----------------------------------

 

 
logs找到了，提示的是证书已过期...
 
但是我浏览器里确实是可以打开的，没有任何错误。
 
另外，日志中明文记录了我的账户信息...
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by CKylinMC** [comment]
我是今天部署的时候申请的Let's Encrypt的证书，而且我也尝试过一层Cloudflare的代理，两个方式都会在连接时提示证书过期，但是浏览器里面看到证书都是有效的。服务器时间和本地时间我也尝试重新校准了，依然提示证书过期...

**Comment by CKylinMC** [comment]
把强制HTTPS关闭后可以访问(HTTP)。

**Comment by TankNee** [comment]
> 当网络出现问题或服务器出现问题时，登出切换账户也是无法进行的，这是刚刚发现的。希望可以有强制登出的方式。

了解了，刚考完研，有时间我看看。
